import type { Metadata } from "next";
import { Toaster } from 'sonner';
import { Noto_Sans_Georgian } from "next/font/google";
import { FavoritesProvider } from "@/contexts/FavoritesContext";
import { FilterDataProvider } from "@/contexts/FilterDataContext";
import "./globals.css";

const georgian = Noto_Sans_Georgian({
  subsets: ["georgian"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Feel DB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon.svg" />
      </head>

      <body className={georgian.className}>
        <FavoritesProvider>
          <FilterDataProvider>
            {children}
          </FilterDataProvider>
        </FavoritesProvider>
        <Toaster
          position="top-center"
          richColors
          toastOptions={{
            style: { background: '#000000', border: '1px solid #262626' },
          }}
        />
      </body>
    </html>
  );
}