import type { Metadata } from "next";
import { Noto_Sans_Georgian } from "next/font/google";
import "./globals.css";

const georgian = Noto_Sans_Georgian({
  subsets: ["georgian"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Feel DB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={georgian.className}>{children}</body>
    </html>
  );
}
